### ISSUE TITLE
content review complete? 

### ISSUE THREAD

**Issue by sginoza** [rfc-editor/draft-eggert-bcp45bis#15]
@larseggert It appears as though the open issues have been resolved.  Are there any other content updates needed?  Otherwise we will convert the file to XML.

**Comment by larseggert** [comment]
#8 is still open - you should probably close it?

**Comment by sginoza** [comment]
@larseggert ack - it's closed.  Please let me know if any other updates are needed or if we're ready to convert to XML.

**Comment by larseggert** [comment]
Please wait for a bit - there is a discussion whether Susan Harris should remain as a co-author (she recently passed away, but wrote the original BCP45).

**Comment by larseggert** [comment]
So I got a few people suggesting that Susan Harris, the original author of BCP45, should remain as a co-author, since much of the text is still hers. She recently passed away, however.

How do we best handle this? Would you like me to propose a PR that adds her back?

**Comment by sginoza** [comment]
I can easily create a PR -- will do that now.

**Comment by sginoza** [comment]
Ok, please review the text and let me know if any other updates are needed or if we're ready to convert to XML.

**Comment by larseggert** [comment]
I'm fine with the changes.

(I don't quite understand why in the references, the names of the mailing lists have been changed to whatever seems to be in mailman, but I can live with it.)
