### ISSUE TITLE
XML review

### ISSUE THREAD

**Issue by sginoza** [rfc-editor/draft-eggert-bcp45bis#18]
@larseggert Hi Lars - The markdown has been converted to XML.  There is also a PR that includes our additional (XML) updates so you can see the diffs.   Please review and let me know how if the RFC is ready for pub or if there are any additional updates needed.   If the RFC is ready for publication, please also send an ack to rfc-editor@rfc-editor.org so have your final approval in our archive.  

The output files  are here: 
   https://www.rfc-editor.org/authors/rfc9245.txt
   https://www.rfc-editor.org/authors/rfc9245.html
   https://www.rfc-editor.org/authors/rfc9245.pdf
   https://www.rfc-editor.org/authors/rfc9245.xml

**Comment by sginoza** [comment]
@larseggert Hi Lars - just checking to see if these are ready for publication.  If the RFC is ready for publication, please also send an ack to [rfc-editor@rfc-editor.org](mailto:rfc-editor@rfc-editor.org) so we have your final approval in our archive.

**Comment by larseggert** [comment]
Looks good; ship it please!
