### ISSUE TITLE
List moderators

### ISSUE THREAD

**Issue by sginoza** [rfc-editor/draft-eggert-bcp45bis#8]
This text is not clear to us.  Are the moderators intended to encourage the community members
to moderate themselves?  Does "by the community" mean community members police each other?

Original:
   The moderators are intended to
   establish a self-moderation function on the community, by the
   community.

**Comment by larseggert** [comment]
It might be more useful to quote the text in question like this: https://github.com/rfc-editor/draft-eggert-bcp45bis/blob/main/draft-eggert-bcp45bis.md?plain=1#L201-L202

**Comment by larseggert** [comment]
Moderators are selected from the community, and they moderate the community.
